version: '2'

services:
  geoserver:
    build: .
    ports:
      - "8888:8080"
    # docker-compose up works after the command to create a named container as below
    # docker run --name geoserver_data_dir -v /var/lib/geoserver/data alpine /bin/true
    # after creating a geoserver workspace it is maintained if I run docker-compose stop and then start
    volumes_from:
      # reference to the service which has the volume with the preloaded geoserver_data_dir
      - data_dir_conf
  data_dir_conf:
    build: data
    image: geoserverdatadir
    container_name: geoserver_data_dir
    command: /bin/true
    volumes:
      - /var/lib/geoserver/data 

volumes:
  # reference to the named data container that holds the preloaded geoserver data directory 
  geoserver_data_dir: